# Generated by Django 3.1.4 on 2022-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_color',
            field=models.CharField(default='Yellow', max_length=32, verbose_name='폰트 색깔'),
        ),
    ]
